version: '2'
services:
  webdav:
    build: .
    container_name: webdav
    volumes:
      - "/var/dav:/media"
    environment:
      VIRTUAL_HOST: webdav.home
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    restart: always
networks:
  default:
    external:
      name: rpi-nginx-proxy_default
